config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :apps do
    resources :events, except: [:index]
  end

  namespace :api, defaults: { format: :json } do
    match '/events', to: 'events#preflight', via: [:options]
    resources :events, only: [:create]
  end
  get 'welcome/home'
  root 'welcome#home'
end

app/models/app.rb
class App < ActiveRecord::Base
  belongs_to :user
  has_many :events
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :app
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :apps
end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController
  skip_before_action :verify_authenticity_token

  before_filter :set_access_control_headers

  def set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'Content-Type'
  end

  def create
    registered_application = App.find_by(url: request.env['HTTP_ORIGIN'])
    @event = registered_application.events.new(name: params[:name])

    if @event.save
      render json: @event, status: :created
    else
      render json: {errors: @event.errors}, status: :unprocessable_entity
    end
  end

  def preflight
    head 200
  end

  private
  def event_params
    params.require(:event).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def require_sign_in
    unless current_user
      flash[:alert] = "You must be logged in to do that"
      redirect_to root_path
    end
  end
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController

  before_action :require_sign_in, except: [:index, :show]

  def index
    @app = App.all
  end

  def show
    @app = App.find(params[:id])
    @events = @app.events.group_by(&:name)
  end

  def new
    @app = App.new
  end

  def create
    @app = App.new(app_params)
      if @app.save
        flash[:notice] = "Application was created succesfully"
        redirect_to apps_path
      else
        flah[:alert] = "Failed to create application plese try again"
        redirect_to new_app_path
      end
    end

  def destroy
    @app = App.find(params[:id])
    if @app.destroy
      flash[:notice] = "Application was deleted succesfully"
      redirect_to apps_path
    else
      flash[:alert] = "There was an error deleting the application"
      redirect_to apps_path
      end
    end


  private

  def app_params
    params.require(:app).permit(:name, :URL, :id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def show
     @event = Event.find(params[:id])
  end

  def new
    @app = App.find(params[:app_id])
    @event = Event.new
  end

  def create
    @app = App.find(params[:app_id])
    @event = @app.events.build(event_params)

    if @event.save
       flash[:notice] = "Event was saved."
       redirect_to [@app, @event]
    else
      flash.now[:alert] = "There was an error creating the event. Please try again"
      render :new
    end
  end

  private

  def event_params
    params.require(:event).permit(:name)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        # Tell the UserMailer to send a welcome email after save
        UserMailer.welcome_email(@user).deliver_later

        format.html { redirect_to(@user, notice: 'User was successfully created.') }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def form_group_tag(errors, &block)
    css_class = 'form-group'
    css_class << ' has-error' if errors.any?

    content_tag :div, capture(&block), class: css_class
  end
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/apps/index.html.erb
<div class="container title">
  <h1> Registered Applications </h1>
</div>

<div class="register-btn">
  <%= link_to "Register New App", new_app_path, class: 'btn'%>
</div>

<div class="container apps-index">
  <div class="row col-md-8">
    <% @app.each do |app| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading"><%= link_to app.name, app %></h4>
          <small><%= app.URL %></small>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/apps/new.html.erb
<div class="container">
<h1 class="title-all">New Application</h1>
  <div class="col-md-6">
    <%= form_for @app do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', placeholder: "Enter Application name" %>
      </div>
      <div class="form-group">
        <%= f.label :URL %>
        <%= f.text_area :URL, rows: 3, class: 'form-control', placeholder: "Enter App URL" %>
      </div>
      <%= f.submit "Save", class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/apps/show.html.erb
<div class="container">
  <h1 class="title-all"><%=@app.name%></h1>
  <p><%=@app.URL%></p>
  <h2 class="title-all"><%= pluralize(@app.events.count, 'event')%> tracked</h2>
  <div class="app-controls">
   <%= link_to "Delete Application", @app, method: :delete, class: 'btn btn-default', data: { confirm: 'Are you sure you want to delete this application' } %>
   <%= link_to "New Event", new_app_event_path(@app), class: 'btn btn-default' %>
  </div>
    <div class="event-index">
      <% @app.events.each do |event| %>
        <p><%= link_to event.name, app_event_path(@app, event) %> <small> added <%= time_ago_in_words(event.created_at) %> ago </small></p>
      <% end %>

      <div class="chart">
        <h2>Tracked Events</h2>
        <%= pie_chart @app.events.group(:name).count %>
      </div>
    </div>
</div>

app/views/events/_form.html.erb
<%= form_for [app, event] do |f| %>
  <% if event.errors.any? %>
   <div class="alert alert-danger">
     <h4><%= pluralize(event.errors.count, "error") %>.</h4>
     <ul>
       <% event.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
       <% end %>
     </ul>
   </div>
  <% end %>

  <%= form_group_tag(event.errors[:name]) do %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: "Enter event name" %>
  <% end %>

 <div class="form-group">
   <%= f.submit "Save", class: 'btn btn-success' %>
 </div>
<% end %>

app/views/events/new.html.erb
<div class="container">
  <h1 class="title-all">New Event</h1>

  <div class="row">
    <div class="col-md-4">
      <div class="col-md-8">
        <%= render partial: 'form', locals: { app: @app, event: @event} %>
      </div>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="container">
  <h1><%= @event.name %></h1>
  <p>Event details</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Metriks</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet">

    <a id="mobile-nav"><span class="ion-navicon-round"></span></a>
    <span role="presentation" class="home-logo"><%= link_to image_tag("/assets/metriks_logo-4099e61f10c317116ecc685c0aee96e05bec086aab4db147e9ebeb528e29904e.jpg"), welcome_home_path %></span>
    <div class="main-nav">
      <ul class="navigation nav nav-tabs">
        <li role="presentation" class="navbar-link"><%= link_to "Applications", apps_path %></li>
        <li role="presentation" class="navbar-link"><%= link_to "About" %></li>
        <% if user_signed_in? %>
          <div class="user-session">
            Welcome <strong><%= current_user.email %></strong>
          </div>
          <li role="presentation" class="navbar-link"><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
          <li role="presentation" class="navbar-link"><%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
        <% else %>
          <li role="presentation" class="navbar-link pull-right"><%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %></li>
          <li role="presentation" class="navbar-link pull-right"><%= link_to "Sign In", new_user_session_path, :class => 'navbar-link' %></li>
        <% end %>
      </ul>
   </div>
  </head>
  <body>

    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:error] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>

  <%= yield %>

  </body>
</html>

app/views/welcome/home.html.erb
<div class="home-page">

  <div class="home-info">
    <h1 class="cover-heading">API Tracking Service and Reporting.</h1>
    <p class="lead">An analytics service and reporting tool that you can use with web apps to track user activity.</p>
  </div>

  <section class="reg-tag">
    <div class="col-md-3">
      <%= link_to image_tag("reg_2.png"), new_app_path %>
      <h2>Register</h2>
      <h3></h3>
      <p>Register your application and start tracking!</p>
    </div>
    <div class="col-md-3">
      <%= link_to image_tag("learn_more.png") %>
      <h2>Learn More</h2>
      <h3></h3>
      <p>Find out more about Metriks</p>
    </div>
  </section>
</div>